spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
    main:
        allow-bean-definition-overriding: true
server:
    port: ${GATEWAY_PORT:8080}
eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
        ip-address: ${GATEWAY_ADDRESS:localhost}
        instance-id: ${GATEWAY_ADDRESS:localhost}:${GATEWAY_PORT:8080}